services:
  # Node-RED Service
  nodered:
    build: 
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: nodered
    image: paulmarenbach/nodered-mqtt:latest
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
    restart: unless-stopped
    command: >
      sh -c "
        cp -n /usr/src/node-red/node-red_settings.js /data/settings.js &&
        cp -n /usr/src/node-red/flows.json /data/flows.json &&
        npm start
      "

volumes:
  node-red-data: