services:
  nodered:
    build: .
    image: paulmarenbach/nodered-mqtt:latest
    network_mode: host
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
    environment:
      - TZ=Europe/Berlin
    depends_on:
          - mosquitto

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto-config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

volumes:
  node-red-data:
  mosquitto-config:
  mosquitto-data:
  mosquitto-log: