services:
  nodered:
    build: .
    image: nodered-mqtt:latest
    network_mode: host
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
    environment:
      - TZ=Europe/Berlin

volumes:
  node-red-data: