services:
  # Node-RED Service
  nodered:
    build: .
    container_name: nodered
    image: paulmarenbach/nodered-mqtt:latest
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
    restart: unless-stopped
    command: >
      sh -c "
        cp -n /usr/src/node-red/node-red_settings.js /data/settings.js &&
        cp -n /usr/src/node-red/flows.json /data/flows.json &&
        npm start
      "

  # Mosquitto MQTT Broker Service
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    restart: unless-stopped

volumes:
  node-red-data:
  mosquitto-data:
  mosquitto-log: